name: Chrome Extension CI
on:
  release:
    types: [published]

jobs:
  build_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: chrome-mru-sliding-tabs-${{ github.event.release.tag_name }}
          path: |
            ./*
            !.git*
